import Head from 'next/head'
import 'antd/dist/antd.css'
import Beranda from './beranda'
import "tailwindcss/tailwind.css"
import Navigasi from './navigasi'
import CarouselAuto from './carousel'
import ContentMain from './customer/content'

import dynamic from 'next/dynamic'

const DynamicHeader = dynamic(() => import("tw-elements"), {
  ssr: false,
})

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="./TW-ELEMENTS-PATH/dist/js/index.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <Navigasi />
      <CarouselAuto />
      <ContentMain />

    </div>
  )
}
